### ISSUE TITLE
.addTo methods don't seem to work

### ISSUE THREAD

**Issue by gregopet** [grails/grails-datastore-test-support#1]
I have a very basic specification involving two domain classes, let's call them Book and Author for familiarity.

A book `belongsTo` a single author and the author `hasMany` books. When using `@TestMixin(HibernateTestMixin)` and `@Domain([Book, Author])`, calling `author.addToBooks(book)`, I get 

```
|  groovy.lang.MissingMethodException: No signature of method: Author.addToBooks() is applicable for argument types: (Book) values: [Book : (unsaved)]
Possible solutions: getBooks()
```

I tried adding the test to this repository but building and running it would seem to require me to get and build a whole bunch of Grails classes :(

**Comment by PipC** [comment]
It seems still not works in Grails 2.4.4.
No signature of method: packName.domainB.addToDomainA() is applicable for argument types: (packName.domainA) values: [packName.domainA : ABC]. Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: packName.domainB.addToDomainB() is applicable for argument types: (packName.domainA) values: [packName.domainA : ABC]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56) ...

**Comment by vijeetgv** [comment]
I got this error also in Grails 2.5.1. Happens only in test cases.

groovy.lang.MissingMethodException: No signature of method: com.zub.Brand.addToAppDomainA() is applicable for argument types: (java.util.LinkedHashMap) values: [DomainBinstance]
