### ISSUE TITLE
How can I change the default Datasource configuration? 

### ISSUE THREAD

**Issue by moonrockfamily** [grails/grails-datastore-test-support#3]
I have a multi-schema domain model and the schema update fails because the in-memory DB doesn't have the schema's...  I was attempting to specify a connection initialization operation, but it doesn't seem to pick up the grails datasource config.

**Comment by jameskleeh** [comment]
You can modify your H2 URL to something like this:

`url = "jdbc:h2:mem:testDb;INIT=CREATE SCHEMA IF NOT EXISTS FOO\\;CREATE SCHEMA IF NOT EXISTS BAR;"`
